SET SCHEMA FN71958;

CREATE OR REPLACE TRIGGER UST_MDF_TRIG
    AFTER INSERT ON HAS
    REFERENCING NEW AS N
    FOR EACH ROW
        BEGIN
            DECLARE cnt INTEGER DEFAULT 0;
            CALL FN71958.COUNTCARSWITHMODIFICATION(N.KIND_MODIFICATION,cnt);
            CALL DBMS_OUTPUT.PUT_LINE(N.KIND_MODIFICATION || ' already has ' ||
                                      cnt || ' cars that can get it.');
        END;

CREATE TABLE CAR_INST(
    NAME_DEALERSHIP VARCHAR(50),
    VIN VARCHAR(17),
    INST_DATE DATE);

CREATE OR REPLACE TRIGGER INST_CAR
    AFTER INSERT ON OWNS
    REFERENCING NEW AS N
    FOR EACH ROW
        BEGIN
            INSERT INTO CAR_INST(NAME_DEALERSHIP, VIN, INST_DATE)
            VALUES (N.CAR_DEALERSHIP_NAME, N.VIN, CURRENT_DATE );
        end;

INSERT INTO CARS(VIN, TYPE, MODEL, ENGINE, TRANSMISSION, EXTERIOR_INTERIOR, COLOR, BASE_PRICE) VALUES ('WDDHF2EB7CA522023', 'Limousines', 'E500 (W212)', '5.5 V8 - 388HP - Petrol', 'Automatic', 'Exterior - Standard Pack & Interior - Standard Pack', 'Black', 145000.00);
INSERT INTO OWNS(CAR_DEALERSHIP_NAME, VIN) VALUES ('Mercedes - Varna', 'WDDHF2EB7CA522023');

INSERT INTO HAS(VIN, KIND_MODIFICATION) VALUES ('WDDHF2EB7CA522023', 'Medium Pack - Exterior & Interior');
INSERT INTO HAS(VIN, KIND_MODIFICATION) VALUES ('WDDHF2EB7CA522023', 'Premium Pack - Exterior & Interior');
INSERT INTO HAS(VIN, KIND_MODIFICATION) VALUES ('WDDHF2EB7CA522023', 'AMG Pack - Exterior & Interior');
INSERT INTO HAS(VIN, KIND_MODIFICATION) VALUES ('WDDHF2EB7CA522023', 'AMG - Alloy Wheels 21');
INSERT INTO HAS(VIN, KIND_MODIFICATION) VALUES ('WDDHF2EB7CA522023', 'Burmester High - End 4D Surround');
