SET SCHEMA FN71958;

CREATE OR REPLACE FUNCTION PRICEALLMODIFICAFION(vin_p char(17))
RETURNS DECIMAL(9,2)
RETURN
SELECT SUM(PRICE)
FROM CARS C, HAS H, MODIFICATIONS MS
WHERE C.VIN = H. VIN AND MS.KIND_MODIFICATION = H.KIND_MODIFICATION AND C.VIN = vin_p;

CREATE OR REPLACE FUNCTION CARSPRICEWITHMODIFICATION(vin_p char(17))
RETURNS DECIMAL(9,2)
RETURN
SELECT BASE_PRICE + FN71958.PRICEALLMODIFICAFION(vin_p)
FROM CARS
WHERE CARS.VIN = vin_p;

SELECT VIN, FN71958.PRICEALLMODIFICAFION(VIN) FROM CARS;
SELECT VIN, FN71958.CARSPRICEWITHMODIFICATION(VIN) FROM CARS;