SET SCHEMA FN71958;

CREATE TABLE CARDEALERSHIPS(
    NAME VARCHAR(50) NOT NULL PRIMARY KEY,
    ADDRESS VARCHAR(300) NOT NULL,
    CITY VARCHAR(50) NOT NULL
);

CREATE TABLE CARS(
    VIN VARCHAR(17) NOT NULL PRIMARY KEY,
    TYPE VARCHAR(50) NOT NULL,
    MODEL VARCHAR(50) NOT NULL,
    ENGINE VARCHAR(50) NOT NULL,
    TRANSMISSION VARCHAR(50) NOT NULL,
    EXTERIOR_INTERIOR VARCHAR(150) NOT NULL,
    COLOR VARCHAR(50) NOT NULL,
    BASE_PRICE INTEGER NOT NULL
);

ALTER TABLE CARS ADD CONSTRAINT CK_CAR_TYPE CHECK (TYPE IN('Limousines', 'Coupe', 'SUV', 'Convertible'));
ALTER TABLE CARS ALTER COLUMN BASE_PRICE SET DATA TYPE DOUBLE;

CREATE TABLE MODIFICATIONS(
    KIND_MODIFICATION VARCHAR(50) NOT NULL PRIMARY KEY,
    PRICE INTEGER NOT NULL
);

ALTER TABLE MODIFICATIONS ALTER COLUMN PRICE SET DATA TYPE DOUBLE;

CREATE TABLE SERVICES(
    KIND_SERVICE VARCHAR(50) NOT NULL PRIMARY KEY,
    DESCRIPTION_OF_SERVICE VARCHAR(300) NOT NULL,
    PRICE INTEGER
);

CREATE TABLE STAFF(
    SNUM VARCHAR(10) NOT NULL PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    PHONE VARCHAR(10) NOT NULL,
    EMAIL VARCHAR(30) CHECK (EMAIL LIKE '%_@_%.__%'),
    POSITION VARCHAR(50),
    CAR_DEALERSHIP_NAME VARCHAR(50) NOT NULL,
    CONSTRAINT FK_STAFF_CAR_DEALERSHIPS FOREIGN KEY(CAR_DEALERSHIP_NAME) REFERENCES CARDEALERSHIPS(NAME)
);

CREATE TABLE CLIENTS(
    PHONE VARCHAR(10) NOT NULL PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    ADDRESS VARCHAR(300) NOT NULL,
    EMAIL VARCHAR(30) CHECK (EMAIL LIKE '%_@_%.__%'),
    CAR VARCHAR(50),
    ANNUAL_CHECK_UP VARCHAR(50),
    SERVICE_HISTORY VARCHAR(300)
);

CREATE TABLE OFFERS(
    CAR_DEALERSHIP_NAME VARCHAR(50) NOT NULL,
    CONSTRAINT FK_NAME_CAR_DEALERSHIPS FOREIGN KEY(CAR_DEALERSHIP_NAME) REFERENCES CARDEALERSHIPS(NAME),
    KIND_SERVICE VARCHAR(50) NOT NULL,
    CONSTRAINT FK_KIND_SERVICE FOREIGN KEY(KIND_SERVICE) REFERENCES SERVICES(KIND_SERVICE)
);

CREATE TABLE OWNS(
    CAR_DEALERSHIP_NAME VARCHAR(50) NOT NULL,
    CONSTRAINT FK_NAME_CAR_DEALERSHIPS FOREIGN KEY(CAR_DEALERSHIP_NAME) REFERENCES CARDEALERSHIPS(NAME),
    VIN VARCHAR(17) NOT NULL,
    CONSTRAINT FK_VIN_CAR FOREIGN KEY (VIN) REFERENCES CARS(VIN)
);

CREATE TABLE HAS(
    VIN VARCHAR(17) NOT NULL,
    CONSTRAINT FK_VIN_CAR FOREIGN KEY (VIN) REFERENCES CARS(VIN),
    KIND_MODIFICATION VARCHAR(50) NOT NULL,
    CONSTRAINT FK_KIND_MODIFICATION FOREIGN KEY (KIND_MODIFICATION) REFERENCES MODIFICATIONS(KIND_MODIFICATION)
);

CREATE TABLE USE(
    PHONE_CLIENT VARCHAR(10) NOT NULL,
    CONSTRAINT FK_PHONE_CLIENT FOREIGN KEY (PHONE_CLIENT) REFERENCES CLIENTS(PHONE),
    SNUM_STAFF VARCHAR(10) NOT NULL,
    CONSTRAINT FK_SNUM_STAFF FOREIGN KEY (SNUM_STAFF) REFERENCES STAFF(SNUM),
    KIND_SERVICE VARCHAR(50) NOT NULL,
    CONSTRAINT FK_KIND_SERVICE FOREIGN KEY (KIND_SERVICE) REFERENCES SERVICES(KIND_SERVICE)
);

CREATE TABLE BUY(
    PHONE_CLIENT VARCHAR(10) NOT NULL,
    CONSTRAINT FK_PHONE_CLIENT FOREIGN KEY (PHONE_CLIENT) REFERENCES CLIENTS(PHONE),
    SNUM_STAFF VARCHAR(10) NOT NULL,
    CONSTRAINT FK_SNUM_STAFF FOREIGN KEY (SNUM_STAFF) REFERENCES STAFF(SNUM),
    VIN VARCHAR(17) NOT NULL,
    CONSTRAINT FK_VIN_CAR FOREIGN KEY (VIN) REFERENCES CARS(VIN)
);